# Generated by Django 2.2 on 2021-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_phone',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
